### ISSUE TITLE
Strange glitch with search

### ISSUE THREAD

**Issue by nrako** [rockymadden/tomorrow-night-eighties-syntax-theme#2] opened 2014-07-16 08:12 UTC
I don't understand why, but that's not just in the search bar it also break the search results. 

![glitch](https://cloud.githubusercontent.com/assets/425397/3596165/73288e64-0cc0-11e4-970f-b3ddaa6db688.gif)

**Comment by ryansobol** [comment] 2015-10-21 16:04
Sorry that I was never able to reproduce the issue. Given that so much has changed about Atom in the 15 months since this issue was created, I'm going to close it. However, please feel free to re-open it if the bug is still somehow present for you.

**Closed by ryansobol** 2015-10-21 16:04 UTC
